/* Tabs, statuses, options, areas, professions and help texts. English → [Estonian, Russian]. */
export default {
  // tabs and statuses
  'All': ['Kõik', 'Все'], 'Drafts': ['Mustandid', 'Черновики'], 'Matching': ['Sobitamine', 'Подбор'], 'Shortlist ready': ['Lühinimekiri valmis', 'Шорт-лист готов'], 'Hired': ['Palgatud', 'Нанят'], 'Closed': ['Suletud', 'Закрыт'],
  'In review': ['Ülevaatusel', 'На рассмотрении'], 'Read by a person': ['Inimene luges', 'Прочитан человеком'],
  'Released': ['Vabastatud', 'Выплачено'], 'Delivered · review': ['Üle antud · ülevaatusel', 'Сдано · на проверке'], 'Not funded': ['Rahastamata', 'Не оплачен'], 'Funded': ['Rahastatud', 'Оплачен'], 'Waiting to accept': ['Ootab nõustumist', 'Ждёт согласия'],
  'Waiting for them to accept': ['Ootab nende nõustumist', 'Ждём согласия'], 'Accept or decline': ['Nõustu või keeldu', 'Примите или отклоните'], 'Declined': ['Tagasi lükatud', 'Отклонено'], 'Withdrawn': ['Tagasi võetud', 'Отозвано'],
  'Completed · review due': ['Lõpetatud · oodatakse tagasisidet', 'Завершено · ждём отзыв'], 'Completed': ['Lõpetatud', 'Завершено'], 'Needs your review': ['Vajab teie ülevaatust', 'Ждёт вашей проверки'],
  'Waiting for client': ['Ootab klienti', 'Ждём клиента'], 'Fund to continue': ['Jätkamiseks rahastage', 'Оплатите, чтобы продолжить'], 'Waiting for funding': ['Ootab rahastamist', 'Ждёт оплаты'],
  'Needs you': ['Vajab teid', 'Требует вас'], 'For you': ['Teile', 'Для вас'], 'Team seats': ['Kohad meeskondades', 'Места в командах'], 'Proposals sent': ['Saadetud pakkumised', 'Отправленные предложения'],
  'Overview': ['Ülevaade', 'Обзор'], 'Security': ['Turvalisus', 'Безопасность'], 'Privacy & data': ['Privaatsus ja andmed', 'Конфиденциальность и данные'], 'Tax & invoicing': ['Maksud ja arved', 'Налоги и счета'], 'Organizations': ['Organisatsioonid', 'Организации'],
  'Identity': ['Isik', 'Личность'], 'Skills test': ['Oskuste test', 'Тест навыков'], 'References': ['Soovitused', 'Рекомендации'], 'Interview': ['Intervjuu', 'Интервью'],
  // proposal start
  'Now': ['Kohe', 'Сейчас'], 'In 1 week': ['1 nädala pärast', 'Через неделю'], 'In 2 weeks': ['2 nädala pärast', 'Через 2 недели'], 'Next month': ['Järgmisel kuul', 'В следующем месяце'],
  // areas
  'Development': ['Arendus', 'Разработка'], 'Payments': ['Maksed', 'Платежи'], 'Design': ['Disain', 'Дизайн'], 'Business Support': ['Äritugi', 'Бизнес-поддержка'], 'Content': ['Sisu', 'Контент'], 'Data & Infrastructure': ['Andmed ja infrastruktuur', 'Данные и инфраструктура'], 'Quality & Security': ['Kvaliteet ja turvalisus', 'Качество и безопасность'],
  // professions
  'Backend Developer': ['Backend-arendaja', 'Backend-разработчик'], 'Frontend Developer': ['Frontend-arendaja', 'Frontend-разработчик'], 'Fullstack Developer': ['Fullstack-arendaja', 'Fullstack-разработчик'], 'Mobile Developer': ['Mobiiliarendaja', 'Мобильный разработчик'], 'DevOps Engineer': ['DevOps-insener', 'DevOps-инженер'], 'QA Engineer': ['QA-insener', 'QA-инженер'], 'Team Lead': ['Meeskonnajuht', 'Тимлид'],
  'Payments Operations Specialist': ['Maksete operatsioonide spetsialist', 'Специалист по платёжным операциям'], 'Payment Integrations Engineer': ['Makseintegratsioonide insener', 'Инженер платёжных интеграций'], 'AML / KYC Analyst': ['AML / KYC analüütik', 'Аналитик AML / KYC'], 'Compliance Officer': ['Vastavusjuht', 'Комплаенс-офицер'], 'Reconciliation Analyst': ['Tasaarvestuse analüütik', 'Аналитик по сверке'], 'Chargeback & Disputes Specialist': ['Tagasinõuete ja vaidluste spetsialist', 'Специалист по чарджбэкам и спорам'], 'Head of Payments': ['Maksete juht', 'Руководитель платежей'],
  'UI/UX Designer': ['UI/UX disainer', 'UI/UX-дизайнер'], 'Product Designer': ['Tootedisainer', 'Продуктовый дизайнер'], 'Graphic Designer': ['Graafiline disainer', 'Графический дизайнер'], 'Brand Designer': ['Brändidisainer', 'Бренд-дизайнер'], 'Motion Designer': ['Motion-disainer', 'Моушн-дизайнер'],
  'Marketing Lead': ['Turundusjuht', 'Руководитель маркетинга'], 'SMM Manager': ['Sotsiaalmeedia juht', 'SMM-менеджер'], 'Content Writer': ['Sisukirjutaja', 'Контент-райтер'], 'Performance Marketer': ['Performance-turundaja', 'Performance-маркетолог'], 'SEO Specialist': ['SEO-spetsialist', 'SEO-специалист'],
  'Project Manager': ['Projektijuht', 'Проектный менеджер'], 'Product Manager': ['Tootejuht', 'Продакт-менеджер'], 'Business Analyst': ['Ärianalüütik', 'Бизнес-аналитик'], 'Customer Support': ['Klienditugi', 'Поддержка клиентов'], 'Accountant': ['Raamatupidaja', 'Бухгалтер'],
  'Copywriter': ['Tekstikirjutaja', 'Копирайтер'], 'Translator': ['Tõlkija', 'Переводчик'], 'Technical Writer': ['Tehniline kirjutaja', 'Технический писатель'], 'Video Editor': ['Videotoimetaja', 'Видеомонтажёр'],
  'Data Engineer': ['Andmeinsener', 'Дата-инженер'], 'Data Analyst': ['Andmeanalüütik', 'Аналитик данных'], 'Cloud Engineer': ['Pilveinsener', 'Облачный инженер'], 'Database Administrator': ['Andmebaasi administraator', 'Администратор БД'],
  'QA Automation Engineer': ['QA automatiseerimise insener', 'Инженер автоматизации QA'], 'Security Engineer': ['Turvainsener', 'Инженер по безопасности'], 'Penetration Tester': ['Läbistustestija', 'Пентестер'],
  'Senior Developer': ['Senior-arendaja', 'Senior-разработчик'], 'Developer': ['Arendaja', 'Разработчик'], 'Operations Manager': ['Operatsioonijuht', 'Операционный менеджер'], 'Admin Assistant': ['Administratiivassistent', 'Административный ассистент'],
  // budgets and starts
  'Under €1k': ['Alla 1k €', 'До 1 тыс. €'], '€1–5k': ['1–5k €', '1–5 тыс. €'], '€5–15k': ['5–15k €', '5–15 тыс. €'], '€15k+': ['15k+ €', 'от 15 тыс. €'],
  '€30–45 / h': ['30–45 € / h', '30–45 € / ч'], '€45–60 / h': ['45–60 € / h', '45–60 € / ч'], '€60–80 / h': ['60–80 € / h', '60–80 € / ч'], '€80+ / h': ['80+ € / h', 'от 80 € / ч'],
  '€5–10k / mo': ['5–10k € / kuu', '5–10 тыс. € / мес.'], '€10–20k / mo': ['10–20k € / kuu', '10–20 тыс. € / мес.'], '€20–40k / mo': ['20–40k € / kuu', '20–40 тыс. € / мес.'], '€40k+ / mo': ['40k+ € / kuu', 'от 40 тыс. € / мес.'],
  '€2–3.5k / mo gross': ['2–3,5k € / kuu bruto', '2–3,5 тыс. € / мес. брутто'], '€3.5–5k / mo gross': ['3,5–5k € / kuu bruto', '3,5–5 тыс. € / мес. брутто'], '€5–7k / mo gross': ['5–7k € / kuu bruto', '5–7 тыс. € / мес. брутто'], '€7k+ / mo gross': ['7k+ € / kuu bruto', 'от 7 тыс. € / мес. брутто'],
  'Not sure: help me scope': ['Pole kindel: aidake hinnata', 'Не уверен(а): помогите оценить'], 'Help me scope': ['Aidake hinnata', 'Помогите оценить'], 'Not set': ['Määramata', 'Не указан'],
  'As soon as possible': ['Nii kiiresti kui võimalik', 'Как можно скорее'], 'Within 2 weeks': ['2 nädala jooksul', 'В течение 2 недель'], 'Within a month': ['Kuu jooksul', 'В течение месяца'], 'Just exploring': ['Lihtsalt uurin', 'Просто изучаю'], 'ASAP': ['Kohe', 'Срочно'], 'Not sure': ['Pole kindel', 'Не уверен(а)'],
  // countries and options
  'Anywhere in the EU': ['Kõikjal ELis', 'Любая страна ЕС'], 'Baltics': ['Baltikum', 'Прибалтика'], 'Nordics + Baltics': ['Põhjamaad + Baltikum', 'Северные страны + Прибалтика'],
  'Checked specialists + AfterWorc shortlist (recommended)': ['Kontrollitud spetsialistid + AfterWorci lühinimekiri (soovitatav)', 'Проверенные специалисты + шорт-лист AfterWorc (рекомендуем)'], 'Only people I invite': ['Ainult minu kutsutud inimesed', 'Только приглашённые мной'],
  'Estonia': ['Eesti', 'Эстония'], 'Latvia': ['Läti', 'Латвия'], 'Lithuania': ['Leedu', 'Литва'], 'Finland': ['Soome', 'Финляндия'], 'Poland': ['Poola', 'Польша'], 'Germany': ['Saksamaa', 'Германия'], 'Portugal': ['Portugal', 'Португалия'], 'Spain': ['Hispaania', 'Испания'], 'Netherlands': ['Holland', 'Нидерланды'], 'Ireland': ['Iirimaa', 'Ирландия'], 'United Kingdom': ['Suurbritannia', 'Великобритания'], 'Ukraine': ['Ukraina', 'Украина'], 'Georgia': ['Gruusia', 'Грузия'], 'Other': ['Muu', 'Другая'], 'Sweden': ['Rootsi', 'Швеция'], 'Other EU': ['Muu ELi riik', 'Другая страна ЕС'],
  'Full-time, permanent': ['Täistööaeg, tähtajatu', 'Полный день, бессрочно'], 'Full-time, fixed term': ['Täistööaeg, tähtajaline', 'Полный день, срочный'], 'Part-time': ['Osaline tööaeg', 'Неполный день'],
  'From next week': ['Alates järgmisest nädalast', 'Со следующей недели'], 'From next month': ['Alates järgmisest kuust', 'Со следующего месяца'], 'Not available': ['Pole saadaval', 'Недоступен'],
  'VAT registered': ['Käibemaksukohustuslane', 'Плательщик НДС'], 'Not registered': ['Pole registreeritud', 'Не зарегистрирован'],
  'Can hire': ['Võib palgata', 'Может нанимать'], 'View only': ['Ainult vaatamine', 'Только просмотр'], 'Finance': ['Finants', 'Финансы'], 'Owner': ['Omanik', 'Владелец'],
  // notification preferences
  'Shortlist ready / new invitation': ['Lühinimekiri valmis / uus kutse', 'Шорт-лист готов / новое приглашение'], 'Work delivered or report to approve': ['Töö üle antud või aruanne kinnitamiseks', 'Работа сдана или отчёт на одобрение'], 'Payment released or received': ['Makse vabastatud või saadud', 'Платёж выплачен или получен'], 'Card payments and declines': ['Kaardimaksed ja tagasilükkamised', 'Платежи по карте и отказы'], 'New message': ['Uus sõnum', 'Новое сообщение'], 'Product news from AfterWorc': ['AfterWorci tootetuudised', 'Новости AfterWorc'],
  // help topics
  'A deal or payment': ['Tehing või makse', 'Сделка или платёж'], 'My brief or shortlist': ['Minu lähteülesanne või lühinimekiri', 'Мой бриф или шорт-лист'], 'Hiring abroad (EOR)': ['Palkamine välismaal (EOR)', 'Найм за рубежом (EOR)'], 'Getting checked': ['Kontrolli läbimine', 'Прохождение проверки'], 'The AfterWorc card': ['AfterWorci kaart', 'Карта AfterWorc'], 'A technical problem': ['Tehniline probleem', 'Техническая проблема'], 'My account': ['Minu konto', 'Мой аккаунт'], 'Something else': ['Midagi muud', 'Другое'],
  // FAQ
  'When is my money released?': ['Millal minu raha vabastatakse?', 'Когда выплачиваются деньги?'],
  'When the client accepts a delivery, or automatically 7 days after delivery if the client does nothing. Released money is on your Working balance at once.': ['Kui klient töö vastu võtab või automaatselt 7 päeva pärast üleandmist, kui klient midagi ei tee. Vabastatud raha on kohe teie tööde saldol.', 'Когда клиент принимает работу или автоматически через 7 дней после сдачи, если клиент ничего не сделал. Выплаченные деньги сразу поступают на рабочий баланс.'],
  'What does "Checked in person" mean?': ['Mida tähendab „Isiklikult kontrollitud“?', 'Что значит «Проверен лично»?'],
  "A person on our team verified the specialist's identity, tested their skills, called two references and interviewed them live. The profile shows who checked and when.": ['Meie meeskonna liige tuvastas spetsialisti isiku, testis tema oskusi, helistas kahele soovitajale ja intervjueeris teda reaalajas. Profiilil on näha, kes ja millal kontrollis.', 'Сотрудник нашей команды подтвердил личность специалиста, проверил навыки, позвонил двум рекомендателям и провёл живое интервью. В профиле видно, кто и когда проверял.'],
  'How do departments get invoiced?': ['Kuidas osakondadele arveid esitatakse?', 'Как выставляются счета за отделы?'],
  'One VAT invoice per month for the whole team, issued when you fund the month.': ['Üks käibemaksuarve kuus kogu meeskonnale, väljastatakse kuu rahastamisel.', 'Один счёт с НДС в месяц на всю команду, выставляется при оплате месяца.'],
  'How does hiring abroad (EOR) work?': ['Kuidas toimib palkamine välismaal (EOR)?', 'Как работает найм за рубежом (EOR)?'],
  'We become the legal employer in the person’s country: contract, payroll, taxes, benefits and on-time pay. You direct the work and get one monthly invoice.': ['Meist saab inimese riigis ametlik tööandja: leping, palgaarvestus, maksud, hüvitised ja õigeaegne palk. Teie juhite tööd ja saate ühe kuuarve.', 'Мы становимся официальным работодателем в стране сотрудника: договор, зарплата, налоги, льготы и выплаты вовремя. Вы руководите работой и получаете один счёт в месяц.'],
  'What if I disagree with a delivery?': ['Mis siis, kui ma üleantud tööga ei nõustu?', 'Что, если я не согласен со сданной работой?'],
  "Request changes with specifics; the review clock restarts on resubmission. If you still can't agree, open an issue on the deal and we mediate within 2 business days.": ['Paluge konkreetseid muudatusi; ülevaatusaeg algab uuesti pärast uut esitamist. Kui ikka kokkuleppele ei jõua, avage tehingus vaidlus ja me vahendame 2 tööpäeva jooksul.', 'Запросите конкретные правки; срок проверки начнётся заново после повторной сдачи. Если договориться не удаётся, откройте спор по сделке — мы выступим посредником в течение 2 рабочих дней.'],
  'How does the AfterWorc card work?': ['Kuidas AfterWorci kaart toimib?', 'Как работает карта AfterWorc?'],
  'It spends from your Available balance only. Held deal money is never touched. Freeze it, set limits and switch ATM and online payments on or off in Money › Card.': ['Kaart kulutab ainult saadaolevat saldot. Tehingutes kinni hoitud raha ei puudutata. Külmutage, seadke limiite ning lülitage sularaha ja veebimakseid sisse või välja jaotises Raha › Kaart.', 'Карта списывает только с доступного баланса. Деньги, зарезервированные в сделках, не затрагиваются. Замораживайте, задавайте лимиты и включайте банкоматы и онлайн-платежи в разделе Деньги › Карта.'],
  'My card was declined. Why?': ['Minu kaart lükati tagasi. Miks?', 'Мою карту отклонили. Почему?'],
  "Check that the card isn't frozen, that the channel (online, contactless, ATM, abroad) is switched on, that you are within your limits, and that Available covers the payment.": ['Kontrollige, et kaart pole külmutatud, et kanal (veeb, kontaktivaba, sularaha, välismaa) on sisse lülitatud, et olete limiitide piires ja et saadaolev saldo katab makse.', 'Проверьте, что карта не заморожена, нужный канал (онлайн, бесконтактно, банкомат, за рубежом) включён, лимиты не превышены и доступного баланса хватает.'],
  'Calls do not connect. What can I do?': ['Kõned ei ühendu. Mida teha?', 'Звонки не соединяются. Что делать?'],
  'Allow the microphone (and camera) for afterworc.com in your browser, and make sure the other person is online. On strict office networks a call may need a TURN server: tell technical support.': ['Lubage brauseris afterworc.com-ile mikrofon (ja kaamera) ning veenduge, et teine inimene on võrgus. Rangetes kontorivõrkudes võib kõne vajada TURN-serverit: andke teada tehnilisele toele.', 'Разрешите в браузере микрофон (и камеру) для afterworc.com и убедитесь, что собеседник в сети. В строгих корпоративных сетях может понадобиться TURN-сервер — сообщите в техподдержку.']
};
